// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCromBw78PphZ4AzmfKTskrxgri99jX_DE',
    appId: '1:386080176174:web:5cb0c2fce9f80688b487bf',
    messagingSenderId: '386080176174',
    projectId: 'flashchatabhi',
    authDomain: 'flashchatabhi.firebaseapp.com',
    storageBucket: 'flashchatabhi.appspot.com',
    measurementId: 'G-TTHFXL2FQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyFD-oaujS0Pk2JA4GyCxCFuhNIdse0v8',
    appId: '1:386080176174:android:d67259cb8a9915bbb487bf',
    messagingSenderId: '386080176174',
    projectId: 'flashchatabhi',
    storageBucket: 'flashchatabhi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG4TvbRo8FxIIGDQ-VEAU-ob0dakd5P2o',
    appId: '1:386080176174:ios:df63a18874d5f583b487bf',
    messagingSenderId: '386080176174',
    projectId: 'flashchatabhi',
    storageBucket: 'flashchatabhi.appspot.com',
    iosClientId: '386080176174-lmk229f2bkgsmr7ml3aghbs27nbon93j.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG4TvbRo8FxIIGDQ-VEAU-ob0dakd5P2o',
    appId: '1:386080176174:ios:df63a18874d5f583b487bf',
    messagingSenderId: '386080176174',
    projectId: 'flashchatabhi',
    storageBucket: 'flashchatabhi.appspot.com',
    iosClientId: '386080176174-lmk229f2bkgsmr7ml3aghbs27nbon93j.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickChat',
  );
}
